### ISSUE TITLE
FileNotFoundError when running  gen_panoptic_seg.py

### ISSUE THREAD

**Issue by zhuzhaohuan** [nesl/radar-camera-fusion-depth#11]
Hi, when I run the gen_panoptic_seg.py file,  the FileNotFound error occurred. 
I'm not sure if it's because I'm running under Windows, so I added '../' before the path code, But there was still an error.
![mmexport1697442285420.png](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/559fe89b-596f-42fd-b212-6cbd1a763ceb)

![mmexport1697442289095.png](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/fc49e45a-74fa-4717-b9f1-df473b926588)

**Comment by zhuzhaohuan** [comment]
The problem has been resolved, and  you need to create your own 'nuscenes_derived/panoptic_segmentation_maskds' folder before running the py file.

**Comment by thecyclone** [comment]
Hi @zhuzhaohuan,

I am bit curious here. Did you not generate the panoptic masks before proceeding to generating training dataset using radarnet before?

**Comment by zhuzhaohuan** [comment]
Yes，I use command to generate the panoptic masks from the beginning. Besides, after I run the setup_dataset_nuscenes.sh,I found that the images in the nuscenes_derived/lidar folder are all black, is there a problem?

**Comment by thecyclone** [comment]
No, they should not be empty. They are sparse so they may look all black on your screen. You should be able to load them using numpy and then check if they contain some values.
