### ISSUE TITLE
Some error about use multiple GPU to train

### ISSUE THREAD

**Issue by zhuzhaohuan** [nesl/radar-camera-fusion-depth#13]
Dear author,
There is no problem when I use a single GPU for training，but when I use 4 GPU and run 'train radarnet.sh', the following error occurred, I couldn't find any problems in the code, I hope you can provide suggestions. Thank you for your reply.
![03c2c5c8836ce5a1c2af6ce4b3a9082](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/765e9d35-2038-4ea6-9298-54ff6948cc15)
![bb76d075de1798f1813871062cd9c9a](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/02020498-90bd-43cd-8fa6-af98da72e530)

**Comment by zhuzhaohuan** [comment]
When using multiple GPUs, if batch size=1, the following issues will be prompted. If the batch size > 1, the problem shown in the above figure will occur.
![0c6060c9da4dbdc353f9514ae7c31f9](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/3691ffb3-712b-47aa-b854-c7be872893a9)

**Comment by thecyclone** [comment]
Hi @zhuzhaohuan ,

Unfortunately, I do not have the means to recreate and debug your issue. I would suggest you try to debug it yourself or use a single GPU for training in the meantime.
