### ISSUE TITLE
inference all nuscenes  CAM_FRONT

### ISSUE THREAD

**Issue by YoungHsu1002** [nesl/radar-camera-fusion-depth#16]
Thx for the great project, I'm figure in how can I inference all CAM_Front data with fusionnet?

**Comment by thecyclone** [comment]
Hi @YoungHsu1002 ,

I am not sure if I understand the question. Can you please elaborate what you want to do?

**Comment by YoungHsu1002** [comment]
I would like to perform inference on every frame inside the CAM_FRONT of the NuScenes dataset, which contains around 34,000 frames. My goal is to generate depth maps for these frames. How can I achieve this?

**Comment by thecyclone** [comment]
You can run inference on both the training-validation and testing datasets. You can make the relevant changes in the test code.

**Comment by YoungHsu1002** [comment]
Thx I'll try it .In addition what's difference between run_fusionet_nuscenes.sh and  run_fusionet_nuscenes_test.sh

**Comment by thecyclone** [comment]
- One is for training-validation set
- One is for testing set

**Comment by YoungHsu1002** [comment]
I thought the same way, but I found that after running run_fusionet_nuscenes.sh, it only produced result.txt and not the images or other data like in the test.

![image](https://github.com/nesl/radar-camera-fusion-depth/assets/146685169/26eeec17-d16c-4693-a1e1-613894aaa406)

Did I missing something details?

**Comment by thecyclone** [comment]
Your bash file is missing the `--save_outputs` parameter when you are running it on training-validation. Just add it in the `run_fusionet_nuscenes.sh` and it should output the data you're looking for.

**Comment by YoungHsu1002** [comment]
Thank you for your assistance; I hadn't noticed that before! Additionally, I would like to ask why the data generated is slightly less than the original nuScenes data. The final result generated was 27,430 + 5,869 + 5,858 (train, val, test) = 39,157. The complete data quantity for nuScenes should be 28,130 + 6,019 + 6,008 = 40,157.

**Comment by thecyclone** [comment]
Issue is continued here: https://github.com/nesl/radar-camera-fusion-depth/issues/17
