### ISSUE TITLE
What is the difference between 'val_ground_truth' and 'val_lidar'

### ISSUE THREAD

**Issue by zhuzhaohuan** [nesl/radar-camera-fusion-depth#18]
Dear author,
In radarnet stage, the gt of val and test is ground_truth.txt , while in fusionnet stage, the gt of val and test is lidar.txt. 
May I ask why the gt of val and test has changed?  Why not use lidar.txt in radarnet stage or use ground_truth.txt in fusionnet stage?
Thank you for your answer.

**Comment by thecyclone** [comment]
RadarNet stage is the intermediate step between the input and the final depth map. We want the output of RadarNet to be dense and hence are using a denser ground truth (calculated using reprojected Lidar frames).

Lidar.txt is the actual ground truth on which we compute the performance of our overall method.

Please also read the data preprocessing section on page 5 of our paper.

**Comment by zhuzhaohuan** [comment]
Thank you very much for your answer. I have resolved my previous questions in the paper.
