### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by XiaoR128** [nesl/radar-camera-fusion-depth#2]
Hi! Thanks for your nice work!
when I run "bash  setup_dataset_nuscenes_radarnet.sh" , forward() missing an argument:'bounding_boxes_list' in line 307 in setup_dataset_nuscenes_radarnet.py 
I will appreciate it if you can solve it!

**Comment by thecyclone** [comment]
Hi @XiaoR128, thanks for catching that. Seems like there was a stale version of some files committed to the repo. 

Please pull the new version and try again. If you find any other such problems, please let me know and I will fix them. Thanks

**Comment by XiaoR128** [comment]
Thanks for your answer! It is pretty effective!
And in the next script "bash train_fusionnet_nuscenes.sh",it seems that a package uformer_model missing in src/fusionnet_model.py line 5(from uformer_model import Uformer, Downsample, Upsample)

**Comment by thecyclone** [comment]
@XiaoR128 it should work now, let me know.

**Comment by XiaoR128** [comment]
OK! It does work! appreciate for your answer
