### ISSUE TITLE
data_utils.py don't have the function ”load_image()“

### ISSUE THREAD

**Issue by CC-owner** [nesl/radar-camera-fusion-depth#24]
radar-camera-fusion-depth-main/setup/setup_dataset_nuscenes.py has such code as followed:

```
###################################################################
line 128
def point_cloud_to_image(nusc,
                         point_cloud,
                         lidar_sensor_token,
                         camera_token,
                         min_distance_from_camera=1.0):

    # Get dictionary of containing path to image, pose, etc.
    camera = nusc.get('sample_data', camera_token)
    lidar_sensor = nusc.get('sample_data', lidar_sensor_token)

    image_path = os.path.join(nusc.dataroot, camera['filename'])
    image = data_utils.load_data(image_path)
####################################################################
```
However, I can't find the function in data_utils.py.
`data_utils.load_data(image_path)`
I was unable to run the following code successfully.
`setup_dataset_nuscenes.py`

**Comment by thecyclone** [comment]
Here's the function: https://github.com/nesl/radar-camera-fusion-depth/blob/1e2cd8f4af5909bf2242acc6fb8caf031ccb7363/setup/data_utils.py#L63

Not sure why you're getting the error. Are you using the bash (.sh) file to run it?

**Comment by thecyclone** [comment]
Okay, Now I see the issue. You're not following the instructions.

To setup the dataset, you're supposed to run the bash file provided here: https://github.com/nesl/radar-camera-fusion-depth/blob/main/bash/setup_dataset_nuscenes.sh

and not the python file. Please follow the instructions.

Here's the load image function if you want it: https://github.com/nesl/radar-camera-fusion-depth/blob/1e2cd8f4af5909bf2242acc6fb8caf031ccb7363/src/data_utils.py#L167

**Comment by CC-owner** [comment]
Oh! Thanks for replying.
