### ISSUE TITLE
The problem of not being able to obtain useful results for the pre trained model of FusionNet

### ISSUE THREAD

**Issue by zhuzhaohuan** [nesl/radar-camera-fusion-depth#28]
Hi authors,
I want to use a pre trained model to generate the final dense depth map. I successfully obtained the result by using ‘module-195000.pth’ in 'setup_dataset_uscenes_radarnet_test. sh'.
But the result I obtained using ‘module-815000.pth’ in 'run_fusionetnuscenes_test. sh' is useless, as shown in the following figure. 
I can obtain effective results by using a model that has undergone simple training instead of ‘module-815000.pth’. I don't understand what caused this situation. Looking forward to your answer, thank you.
![image](https://github.com/nesl/radar-camera-fusion-depth/assets/48746939/2ffafea7-3f61-4519-9445-dcf3e618e9fd)

**Comment by thecyclone** [comment]
If you can obtain meaningful results using a model that you have trained yourself but not using the pre-trained model, there might be an issue with your bash file or the configurations might be different.

I remember you were using multiple GPUs to test and were getting some errors. Maybe start from that.

**Comment by zhuzhaohuan** [comment]
I ran it again and succeeded, although I'm not sure what happened, the problem was resolved.

**Comment by thecyclone** [comment]
> I ran it again and succeeded, although I'm not sure what happened, the problem was resolved.

Glad you were able to solve it. I am closing the issue.
