### ISSUE TITLE
Not obtaining useful results from FusionNET

### ISSUE THREAD

**Issue by IoannaB04** [nesl/radar-camera-fusion-depth#29]
Hello authors,

I am following your instructions to run RadarNet and FusionNet but the results I get are not useful as you can see in the following image

![n015-2018-07-18-11-07-57+0800__CAM_FRONT__1531883530412470](https://github.com/nesl/radar-camera-fusion-depth/assets/103269698/5c51cd05-2766-436a-8710-f385e6a6a43b)

Do you have any idea why?

**Comment by thecyclone** [comment]
This look like the output of RadarNet. I can see some data in the image on the bottom left and bottom right sides.
You can check that the output is not empty using numpy. What do you mean by the results not being useful?

**Comment by IoannaB04** [comment]
Could you please tell me where the depth maps from FusionNET are stored?

**Comment by thecyclone** [comment]
Where ever you want to save them: https://github.com/nesl/radar-camera-fusion-depth/blob/main/bash/run_fusionnet_nuscenes_test.sh

Look at `output_dirpath`

Please read the code files as you run them. They contain the location where the folders are created.
