### ISSUE TITLE
night and rain scenes of nuScenes dataset

### ISSUE THREAD

**Issue by MMOCKING** [nesl/radar-camera-fusion-depth#3]
Hello,

Did you remove night and rain data from the dataset during training and testing? It seems difficult to estimate depth on these data.

**Comment by thecyclone** [comment]
Hi @MMOCKING,

Our data_split is available here: https://github.com/nesl/radar-camera-fusion-depth/tree/main/data_split

The code is here: https://github.com/nesl/radar-camera-fusion-depth/blob/ef9191e12ff91ae00597e0c5ce890559a5aa037d/setup/setup_dataset_nuscenes.py#L1138

[Note that in nuScenes, the scene_id and the number in scene_name are different]

Our training and validation splits follow the standard nuScenes split. We use the entirety of testing set. We did not remove any night or rain scenes on purpose from the dataset.
