### ISSUE TITLE
Accumulated and interpolated lidar depth

### ISSUE THREAD

**Issue by lotterf** [nesl/radar-camera-fusion-depth#30]
![image](https://github.com/nesl/radar-camera-fusion-depth/assets/109028420/15d1638d-60a8-4a8a-babb-60888ca361a1)
Hello, I was wondering how to use your code to generate accumulated and interpolated lidar depth，thanks

**Comment by thecyclone** [comment]
Hi,

Please follow the readme on how to setup the dataset.
