### ISSUE TITLE
how do I run and evaluate fusionnet?

### ISSUE THREAD

**Issue by zhang-xu0124** [nesl/radar-camera-fusion-depth#32]
Hello author, first of all thank you for doing such an outstanding job, I have generated depth and response images from radarnet, how do I run and evaluate fusionnet? How to get nuscenes_train_depth_predicted.txt and nuscenes_train_response_predicted.txt for training? @thecyclone

**Comment by thecyclone** [comment]
Please follow the readme step-by-step.
