### ISSUE TITLE
question with test set

### ISSUE THREAD

**Issue by harborsarah** [nesl/radar-camera-fusion-depth#8]
Dear authors,

In the first stage, we run `bash setup_dataset_nuscenes.sh` to derive the GT maps. However, in the setup/setup_dataset_nuscenes_with_denseGT.py file, only training and validation datasets are generated. So, the testing/ folder is still empty after this bash command is finished. 
I would like to ask if there is no code for generating the test dataset. I checked the `setup_dataset_nuscenes_test.py` file, but it seems a bit different than `setup_dataset_nuscenes_with_denseGT.py` file. Is it possible to just run this `setup_dataset_nuscenes_test.py` file to generate the GT maps for the testing samples?

Thanks for your reply.

**Comment by thecyclone** [comment]
Hi @harborsarah ,

You can just run [setup_dataset_nuscenes_test.sh](https://github.com/nesl/radar-camera-fusion-depth/blob/main/bash/setup_dataset_nuscenes_test.sh) to generate the test set.
