### ISSUE TITLE
How to obtain 'quasi-dense depth' and 'output depth' like in the paper image?

### ISSUE THREAD

**Issue by zhuzhaohuan** [nesl/radar-camera-fusion-depth#9]
Hello, I have finished reading the model structure code for Radarnet and Fusionnet, but I haven't seen how to generate 'quasi-dense depth' and 'output depth'. How did I obtain them? 
Also, may I understand the output map (or output feature map) of Radarnet as the 'quasi-dense depth' itself? Thank you!

**Comment by thecyclone** [comment]
- The output of the RadarNet is the semi-dense or quasi-dense depth map (semi-dense and quasi-dense terms can be used interchangeably) 
- The output of the FusionNet is the output depth

**Comment by zhuzhaohuan** [comment]
Thank you for your reply. I understand now. :D
